name: ${project.name}
version: ${project.version}
main: com.stuntguy3000.minecraft.targetpractice.PluginMain
authors: [ stuntguy3000 ]
api-version: 1.20
commands:
  TargetPractice:
    aliases: [ target ]
permissions:
  targetpractice.use:
    description: Grants player the ability to use this plugin